# Generated by Django 3.2.8 on 2021-10-26 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20211026_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
