# Generated by Django 3.2.8 on 2021-10-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_likes_post_likes_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes_from',
            new_name='like_user',
        ),
    ]
